// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.3
// source: cellphone_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加一台手机信息的请求
type CreateCellphoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cellphone *Cellphone `protobuf:"bytes,1,opt,name=cellphone,proto3" json:"cellphone,omitempty"`
}

func (x *CreateCellphoneRequest) Reset() {
	*x = CreateCellphoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCellphoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCellphoneRequest) ProtoMessage() {}

func (x *CreateCellphoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCellphoneRequest.ProtoReflect.Descriptor instead.
func (*CreateCellphoneRequest) Descriptor() ([]byte, []int) {
	return file_cellphone_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCellphoneRequest) GetCellphone() *Cellphone {
	if x != nil {
		return x.Cellphone
	}
	return nil
}

// 添加一台手机的响应
type CreateCellphoneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateCellphoneResponse) Reset() {
	*x = CreateCellphoneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCellphoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCellphoneResponse) ProtoMessage() {}

func (x *CreateCellphoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCellphoneResponse.ProtoReflect.Descriptor instead.
func (*CreateCellphoneResponse) Descriptor() ([]byte, []int) {
	return file_cellphone_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCellphoneResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 查找手机的查询条件
type FilterCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinCpuCore         int32    `protobuf:"varint,1,opt,name=min_cpu_core,json=minCpuCore,proto3" json:"min_cpu_core,omitempty"`
	MinBatteryCapacity int32    `protobuf:"varint,2,opt,name=min_battery_capacity,json=minBatteryCapacity,proto3" json:"min_battery_capacity,omitempty"`
	MinRamSize         int32    `protobuf:"varint,3,opt,name=min_ram_size,json=minRamSize,proto3" json:"min_ram_size,omitempty"`
	MinStorageSize     int32    `protobuf:"varint,4,opt,name=min_storage_size,json=minStorageSize,proto3" json:"min_storage_size,omitempty"`
	Brands             []string `protobuf:"bytes,5,rep,name=brands,proto3" json:"brands,omitempty"`
}

func (x *FilterCondition) Reset() {
	*x = FilterCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterCondition) ProtoMessage() {}

func (x *FilterCondition) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterCondition.ProtoReflect.Descriptor instead.
func (*FilterCondition) Descriptor() ([]byte, []int) {
	return file_cellphone_service_proto_rawDescGZIP(), []int{2}
}

func (x *FilterCondition) GetMinCpuCore() int32 {
	if x != nil {
		return x.MinCpuCore
	}
	return 0
}

func (x *FilterCondition) GetMinBatteryCapacity() int32 {
	if x != nil {
		return x.MinBatteryCapacity
	}
	return 0
}

func (x *FilterCondition) GetMinRamSize() int32 {
	if x != nil {
		return x.MinRamSize
	}
	return 0
}

func (x *FilterCondition) GetMinStorageSize() int32 {
	if x != nil {
		return x.MinStorageSize
	}
	return 0
}

func (x *FilterCondition) GetBrands() []string {
	if x != nil {
		return x.Brands
	}
	return nil
}

// 上传封面图片的请求
type UploadCellphoneCoverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*UploadCellphoneCoverRequest_Meta
	//	*UploadCellphoneCoverRequest_Block
	Data isUploadCellphoneCoverRequest_Data `protobuf_oneof:"data"`
}

func (x *UploadCellphoneCoverRequest) Reset() {
	*x = UploadCellphoneCoverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadCellphoneCoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCellphoneCoverRequest) ProtoMessage() {}

func (x *UploadCellphoneCoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCellphoneCoverRequest.ProtoReflect.Descriptor instead.
func (*UploadCellphoneCoverRequest) Descriptor() ([]byte, []int) {
	return file_cellphone_service_proto_rawDescGZIP(), []int{3}
}

func (m *UploadCellphoneCoverRequest) GetData() isUploadCellphoneCoverRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *UploadCellphoneCoverRequest) GetMeta() *CoverMetaInfo {
	if x, ok := x.GetData().(*UploadCellphoneCoverRequest_Meta); ok {
		return x.Meta
	}
	return nil
}

func (x *UploadCellphoneCoverRequest) GetBlock() []byte {
	if x, ok := x.GetData().(*UploadCellphoneCoverRequest_Block); ok {
		return x.Block
	}
	return nil
}

type isUploadCellphoneCoverRequest_Data interface {
	isUploadCellphoneCoverRequest_Data()
}

type UploadCellphoneCoverRequest_Meta struct {
	Meta *CoverMetaInfo `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type UploadCellphoneCoverRequest_Block struct {
	Block []byte `protobuf:"bytes,2,opt,name=block,proto3,oneof"`
}

func (*UploadCellphoneCoverRequest_Meta) isUploadCellphoneCoverRequest_Data() {}

func (*UploadCellphoneCoverRequest_Block) isUploadCellphoneCoverRequest_Data() {}

// 封面图片元数据
type CoverMetaInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size      uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ImageType string `protobuf:"bytes,3,opt,name=image_type,json=imageType,proto3" json:"image_type,omitempty"`
}

func (x *CoverMetaInfo) Reset() {
	*x = CoverMetaInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoverMetaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverMetaInfo) ProtoMessage() {}

func (x *CoverMetaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverMetaInfo.ProtoReflect.Descriptor instead.
func (*CoverMetaInfo) Descriptor() ([]byte, []int) {
	return file_cellphone_service_proto_rawDescGZIP(), []int{4}
}

func (x *CoverMetaInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CoverMetaInfo) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CoverMetaInfo) GetImageType() string {
	if x != nil {
		return x.ImageType
	}
	return ""
}

// 上传封面图片后得到的响应
type UploadCellphoneCoverResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *UploadCellphoneCoverResponse) Reset() {
	*x = UploadCellphoneCoverResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadCellphoneCoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCellphoneCoverResponse) ProtoMessage() {}

func (x *UploadCellphoneCoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCellphoneCoverResponse.ProtoReflect.Descriptor instead.
func (*UploadCellphoneCoverResponse) Descriptor() ([]byte, []int) {
	return file_cellphone_service_proto_rawDescGZIP(), []int{5}
}

func (x *UploadCellphoneCoverResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadCellphoneCoverResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type BuyCellphoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *BuyCellphoneRequest) Reset() {
	*x = BuyCellphoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyCellphoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyCellphoneRequest) ProtoMessage() {}

func (x *BuyCellphoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyCellphoneRequest.ProtoReflect.Descriptor instead.
func (*BuyCellphoneRequest) Descriptor() ([]byte, []int) {
	return file_cellphone_service_proto_rawDescGZIP(), []int{6}
}

func (x *BuyCellphoneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuyCellphoneRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BuyCellphoneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Avg float64 `protobuf:"fixed64,2,opt,name=avg,proto3" json:"avg,omitempty"`
}

func (x *BuyCellphoneResponse) Reset() {
	*x = BuyCellphoneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyCellphoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyCellphoneResponse) ProtoMessage() {}

func (x *BuyCellphoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyCellphoneResponse.ProtoReflect.Descriptor instead.
func (*BuyCellphoneResponse) Descriptor() ([]byte, []int) {
	return file_cellphone_service_proto_rawDescGZIP(), []int{7}
}

func (x *BuyCellphoneResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuyCellphoneResponse) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

var File_cellphone_service_proto protoreflect.FileDescriptor

var file_cellphone_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0f, 0x63,
	0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45,
	0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x09, 0x63, 0x65, 0x6c, 0x6c,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x09, 0x63, 0x65, 0x6c, 0x6c,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x29, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43,
	0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0xc9, 0x01, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0c, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x70, 0x75, 0x5f,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x69, 0x6e, 0x43,
	0x70, 0x75, 0x43, 0x6f, 0x72, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x6d, 0x69, 0x6e, 0x5f, 0x62, 0x61,
	0x74, 0x74, 0x65, 0x72, 0x79, 0x5f, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x6d, 0x69, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79,
	0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0c, 0x6d, 0x69, 0x6e, 0x5f,
	0x72, 0x61, 0x6d, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x6d, 0x69, 0x6e, 0x52, 0x61, 0x6d, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x69,
	0x6e, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6d, 0x69, 0x6e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x73, 0x22, 0x66, 0x0a, 0x1b,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x43,
	0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x6d,
	0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x6f, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x06, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x52, 0x0a, 0x0d, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x74,
	0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x42, 0x0a, 0x1c, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x3b, 0x0a, 0x13,
	0x42, 0x75, 0x79, 0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x38, 0x0a, 0x14, 0x42, 0x75, 0x79,
	0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x76, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03,
	0x61, 0x76, 0x67, 0x32, 0xbb, 0x02, 0x0a, 0x10, 0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x65,
	0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x30, 0x01, 0x12, 0x5b, 0x0a,
	0x14, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x43, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x45, 0x0a, 0x0c, 0x42, 0x75,
	0x79, 0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e,
	0x42, 0x75, 0x79, 0x43, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x79, 0x43, 0x65, 0x6c, 0x6c,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_cellphone_service_proto_rawDescOnce sync.Once
	file_cellphone_service_proto_rawDescData = file_cellphone_service_proto_rawDesc
)

func file_cellphone_service_proto_rawDescGZIP() []byte {
	file_cellphone_service_proto_rawDescOnce.Do(func() {
		file_cellphone_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_cellphone_service_proto_rawDescData)
	})
	return file_cellphone_service_proto_rawDescData
}

var file_cellphone_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cellphone_service_proto_goTypes = []interface{}{
	(*CreateCellphoneRequest)(nil),       // 0: pb.CreateCellphoneRequest
	(*CreateCellphoneResponse)(nil),      // 1: pb.CreateCellphoneResponse
	(*FilterCondition)(nil),              // 2: pb.FilterCondition
	(*UploadCellphoneCoverRequest)(nil),  // 3: pb.UploadCellphoneCoverRequest
	(*CoverMetaInfo)(nil),                // 4: pb.CoverMetaInfo
	(*UploadCellphoneCoverResponse)(nil), // 5: pb.UploadCellphoneCoverResponse
	(*BuyCellphoneRequest)(nil),          // 6: pb.BuyCellphoneRequest
	(*BuyCellphoneResponse)(nil),         // 7: pb.BuyCellphoneResponse
	(*Cellphone)(nil),                    // 8: pb.Cellphone
}
var file_cellphone_service_proto_depIdxs = []int32{
	8, // 0: pb.CreateCellphoneRequest.cellphone:type_name -> pb.Cellphone
	4, // 1: pb.UploadCellphoneCoverRequest.meta:type_name -> pb.CoverMetaInfo
	0, // 2: pb.CellphoneService.CreateCellphone:input_type -> pb.CreateCellphoneRequest
	2, // 3: pb.CellphoneService.SearchCellphone:input_type -> pb.FilterCondition
	3, // 4: pb.CellphoneService.UploadCellphoneCover:input_type -> pb.UploadCellphoneCoverRequest
	6, // 5: pb.CellphoneService.BuyCellphone:input_type -> pb.BuyCellphoneRequest
	1, // 6: pb.CellphoneService.CreateCellphone:output_type -> pb.CreateCellphoneResponse
	8, // 7: pb.CellphoneService.SearchCellphone:output_type -> pb.Cellphone
	5, // 8: pb.CellphoneService.UploadCellphoneCover:output_type -> pb.UploadCellphoneCoverResponse
	7, // 9: pb.CellphoneService.BuyCellphone:output_type -> pb.BuyCellphoneResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cellphone_service_proto_init() }
func file_cellphone_service_proto_init() {
	if File_cellphone_service_proto != nil {
		return
	}
	file_cellphone_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cellphone_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCellphoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cellphone_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCellphoneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cellphone_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cellphone_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadCellphoneCoverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cellphone_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoverMetaInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cellphone_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadCellphoneCoverResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cellphone_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyCellphoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cellphone_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyCellphoneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cellphone_service_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*UploadCellphoneCoverRequest_Meta)(nil),
		(*UploadCellphoneCoverRequest_Block)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cellphone_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cellphone_service_proto_goTypes,
		DependencyIndexes: file_cellphone_service_proto_depIdxs,
		MessageInfos:      file_cellphone_service_proto_msgTypes,
	}.Build()
	File_cellphone_service_proto = out.File
	file_cellphone_service_proto_rawDesc = nil
	file_cellphone_service_proto_goTypes = nil
	file_cellphone_service_proto_depIdxs = nil
}
