// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: cellphone.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 内存DDR类型
type DDRType int32

const (
	DDRType_DDR3 DDRType = 0
	DDRType_DDR4 DDRType = 1
	DDRType_DDR5 DDRType = 2
)

// Enum value maps for DDRType.
var (
	DDRType_name = map[int32]string{
		0: "DDR3",
		1: "DDR4",
		2: "DDR5",
	}
	DDRType_value = map[string]int32{
		"DDR3": 0,
		"DDR4": 1,
		"DDR5": 2,
	}
)

func (x DDRType) Enum() *DDRType {
	p := new(DDRType)
	*p = x
	return p
}

func (x DDRType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DDRType) Descriptor() protoreflect.EnumDescriptor {
	return file_cellphone_proto_enumTypes[0].Descriptor()
}

func (DDRType) Type() protoreflect.EnumType {
	return &file_cellphone_proto_enumTypes[0]
}

func (x DDRType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DDRType.Descriptor instead.
func (DDRType) EnumDescriptor() ([]byte, []int) {
	return file_cellphone_proto_rawDescGZIP(), []int{0}
}

// 存储容量单位
type Unit int32

const (
	Unit_UnitMB Unit = 0
	Unit_UnitGB Unit = 1
	Unit_UnitTB Unit = 2
)

// Enum value maps for Unit.
var (
	Unit_name = map[int32]string{
		0: "UnitMB",
		1: "UnitGB",
		2: "UnitTB",
	}
	Unit_value = map[string]int32{
		"UnitMB": 0,
		"UnitGB": 1,
		"UnitTB": 2,
	}
)

func (x Unit) Enum() *Unit {
	p := new(Unit)
	*p = x
	return p
}

func (x Unit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Unit) Descriptor() protoreflect.EnumDescriptor {
	return file_cellphone_proto_enumTypes[1].Descriptor()
}

func (Unit) Type() protoreflect.EnumType {
	return &file_cellphone_proto_enumTypes[1]
}

func (x Unit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Unit.Descriptor instead.
func (Unit) EnumDescriptor() ([]byte, []int) {
	return file_cellphone_proto_rawDescGZIP(), []int{1}
}

// 硬盘类型
type StorageType int32

const (
	// 固态硬盘
	StorageType_SSD StorageType = 0
	// 机械硬盘
	StorageType_HDD StorageType = 2
)

// Enum value maps for StorageType.
var (
	StorageType_name = map[int32]string{
		0: "SSD",
		2: "HDD",
	}
	StorageType_value = map[string]int32{
		"SSD": 0,
		"HDD": 2,
	}
)

func (x StorageType) Enum() *StorageType {
	p := new(StorageType)
	*p = x
	return p
}

func (x StorageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageType) Descriptor() protoreflect.EnumDescriptor {
	return file_cellphone_proto_enumTypes[2].Descriptor()
}

func (StorageType) Type() protoreflect.EnumType {
	return &file_cellphone_proto_enumTypes[2]
}

func (x StorageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageType.Descriptor instead.
func (StorageType) EnumDescriptor() ([]byte, []int) {
	return file_cellphone_proto_rawDescGZIP(), []int{2}
}

// CPU信息
type CPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 生产厂商
	Manufacturer string `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	// 核心数量
	Cores int32 `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`
	// 最小频率
	MinGhz float64 `protobuf:"fixed64,3,opt,name=min_ghz,json=minGhz,proto3" json:"min_ghz,omitempty"`
	// 最大频率
	MaxGhz float64 `protobuf:"fixed64,4,opt,name=max_ghz,json=maxGhz,proto3" json:"max_ghz,omitempty"`
}

func (x *CPU) Reset() {
	*x = CPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPU) ProtoMessage() {}

func (x *CPU) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPU.ProtoReflect.Descriptor instead.
func (*CPU) Descriptor() ([]byte, []int) {
	return file_cellphone_proto_rawDescGZIP(), []int{0}
}

func (x *CPU) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *CPU) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *CPU) GetMinGhz() float64 {
	if x != nil {
		return x.MinGhz
	}
	return 0
}

func (x *CPU) GetMaxGhz() float64 {
	if x != nil {
		return x.MaxGhz
	}
	return 0
}

// 电池信息
type Battery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 电池容量
	Capacity int32 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
}

func (x *Battery) Reset() {
	*x = Battery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Battery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Battery) ProtoMessage() {}

func (x *Battery) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Battery.ProtoReflect.Descriptor instead.
func (*Battery) Descriptor() ([]byte, []int) {
	return file_cellphone_proto_rawDescGZIP(), []int{1}
}

func (x *Battery) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

// 内存信息
type RAM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 内存大小
	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	// 内存大小单位
	Unit Unit `protobuf:"varint,2,opt,name=unit,proto3,enum=pb.Unit" json:"unit,omitempty"`
	// 内存DDR类型
	DdrType DDRType `protobuf:"varint,3,opt,name=ddr_type,json=ddrType,proto3,enum=pb.DDRType" json:"ddr_type,omitempty"`
}

func (x *RAM) Reset() {
	*x = RAM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RAM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAM) ProtoMessage() {}

func (x *RAM) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAM.ProtoReflect.Descriptor instead.
func (*RAM) Descriptor() ([]byte, []int) {
	return file_cellphone_proto_rawDescGZIP(), []int{2}
}

func (x *RAM) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *RAM) GetUnit() Unit {
	if x != nil {
		return x.Unit
	}
	return Unit_UnitMB
}

func (x *RAM) GetDdrType() DDRType {
	if x != nil {
		return x.DdrType
	}
	return DDRType_DDR3
}

// 硬盘信息
type Storage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 硬盘大小
	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	// 存储单位
	Unit Unit `protobuf:"varint,2,opt,name=unit,proto3,enum=pb.Unit" json:"unit,omitempty"`
	// 硬盘类型
	StorageType StorageType `protobuf:"varint,3,opt,name=storage_type,json=storageType,proto3,enum=pb.StorageType" json:"storage_type,omitempty"`
}

func (x *Storage) Reset() {
	*x = Storage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage) ProtoMessage() {}

func (x *Storage) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage.ProtoReflect.Descriptor instead.
func (*Storage) Descriptor() ([]byte, []int) {
	return file_cellphone_proto_rawDescGZIP(), []int{3}
}

func (x *Storage) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Storage) GetUnit() Unit {
	if x != nil {
		return x.Unit
	}
	return Unit_UnitMB
}

func (x *Storage) GetStorageType() StorageType {
	if x != nil {
		return x.StorageType
	}
	return StorageType_SSD
}

// 操作系统
type OperatingSystem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 操作系统名字
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 操作系统版本
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *OperatingSystem) Reset() {
	*x = OperatingSystem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperatingSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatingSystem) ProtoMessage() {}

func (x *OperatingSystem) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatingSystem.ProtoReflect.Descriptor instead.
func (*OperatingSystem) Descriptor() ([]byte, []int) {
	return file_cellphone_proto_rawDescGZIP(), []int{4}
}

func (x *OperatingSystem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OperatingSystem) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// GPU
type GPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 生产厂商
	Manufacturer string `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	// 显存大小
	Memory int32 `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	// 显存单位
	MemoryUnit Unit `protobuf:"varint,3,opt,name=memory_unit,json=memoryUnit,proto3,enum=pb.Unit" json:"memory_unit,omitempty"`
	// 最小频率
	MinGhz float64 `protobuf:"fixed64,4,opt,name=min_ghz,json=minGhz,proto3" json:"min_ghz,omitempty"`
	// 最大频率
	MaxGhz float64 `protobuf:"fixed64,5,opt,name=max_ghz,json=maxGhz,proto3" json:"max_ghz,omitempty"`
}

func (x *GPU) Reset() {
	*x = GPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPU) ProtoMessage() {}

func (x *GPU) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPU.ProtoReflect.Descriptor instead.
func (*GPU) Descriptor() ([]byte, []int) {
	return file_cellphone_proto_rawDescGZIP(), []int{5}
}

func (x *GPU) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *GPU) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *GPU) GetMemoryUnit() Unit {
	if x != nil {
		return x.MemoryUnit
	}
	return Unit_UnitMB
}

func (x *GPU) GetMinGhz() float64 {
	if x != nil {
		return x.MinGhz
	}
	return 0
}

func (x *GPU) GetMaxGhz() float64 {
	if x != nil {
		return x.MaxGhz
	}
	return 0
}

// 屏幕
type Screen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size       float64 `protobuf:"fixed64,1,opt,name=size,proto3" json:"size,omitempty"`
	Resolution string  `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
}

func (x *Screen) Reset() {
	*x = Screen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Screen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screen) ProtoMessage() {}

func (x *Screen) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screen.ProtoReflect.Descriptor instead.
func (*Screen) Descriptor() ([]byte, []int) {
	return file_cellphone_proto_rawDescGZIP(), []int{6}
}

func (x *Screen) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Screen) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

// 相机
type Camera struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brand string `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Spec  string `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *Camera) Reset() {
	*x = Camera{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Camera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Camera) ProtoMessage() {}

func (x *Camera) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Camera.ProtoReflect.Descriptor instead.
func (*Camera) Descriptor() ([]byte, []int) {
	return file_cellphone_proto_rawDescGZIP(), []int{7}
}

func (x *Camera) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Camera) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

// 代表一台手机
type Cellphone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand           string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Cpu             *CPU                   `protobuf:"bytes,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Ram             *RAM                   `protobuf:"bytes,5,opt,name=ram,proto3" json:"ram,omitempty"`
	Gpu             *GPU                   `protobuf:"bytes,6,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Battery         *Battery               `protobuf:"bytes,7,opt,name=battery,proto3" json:"battery,omitempty"`
	Storage         *Storage               `protobuf:"bytes,8,opt,name=storage,proto3" json:"storage,omitempty"`
	OperatingSystem *OperatingSystem       `protobuf:"bytes,9,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	Screen          *Screen                `protobuf:"bytes,10,opt,name=screen,proto3" json:"screen,omitempty"`
	Camera          *Camera                `protobuf:"bytes,11,opt,name=camera,proto3" json:"camera,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Cellphone) Reset() {
	*x = Cellphone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cellphone_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cellphone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cellphone) ProtoMessage() {}

func (x *Cellphone) ProtoReflect() protoreflect.Message {
	mi := &file_cellphone_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cellphone.ProtoReflect.Descriptor instead.
func (*Cellphone) Descriptor() ([]byte, []int) {
	return file_cellphone_proto_rawDescGZIP(), []int{8}
}

func (x *Cellphone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cellphone) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Cellphone) GetCpu() *CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *Cellphone) GetRam() *RAM {
	if x != nil {
		return x.Ram
	}
	return nil
}

func (x *Cellphone) GetGpu() *GPU {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *Cellphone) GetBattery() *Battery {
	if x != nil {
		return x.Battery
	}
	return nil
}

func (x *Cellphone) GetStorage() *Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *Cellphone) GetOperatingSystem() *OperatingSystem {
	if x != nil {
		return x.OperatingSystem
	}
	return nil
}

func (x *Cellphone) GetScreen() *Screen {
	if x != nil {
		return x.Screen
	}
	return nil
}

func (x *Cellphone) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

func (x *Cellphone) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_cellphone_proto protoreflect.FileDescriptor

var file_cellphone_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x71, 0x0a, 0x03, 0x43, 0x50, 0x55, 0x12, 0x22, 0x0a,
	0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x5f, 0x67,
	0x68, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x47, 0x68, 0x7a,
	0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x67, 0x68, 0x7a, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x47, 0x68, 0x7a, 0x22, 0x25, 0x0a, 0x07, 0x42, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x22, 0x61, 0x0a, 0x03, 0x52, 0x41, 0x4d, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a,
	0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x70, 0x62,
	0x2e, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x26, 0x0a, 0x08, 0x64,
	0x64, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e,
	0x70, 0x62, 0x2e, 0x44, 0x44, 0x52, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x64, 0x64, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x71, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x04, 0x75, 0x6e,
	0x69, 0x74, 0x12, 0x32, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3f, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x9e, 0x01, 0x0a, 0x03, 0x47, 0x50, 0x55, 0x12,
	0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x29, 0x0a, 0x0b, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x5f, 0x67, 0x68,
	0x7a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x47, 0x68, 0x7a, 0x12,
	0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x67, 0x68, 0x7a, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x06, 0x6d, 0x61, 0x78, 0x47, 0x68, 0x7a, 0x22, 0x3c, 0x0a, 0x06, 0x53, 0x63, 0x72, 0x65,
	0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x32, 0x0a, 0x06, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0x93, 0x03, 0x0a, 0x09, 0x43,
	0x65, 0x6c, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x19,
	0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x50, 0x55, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x19, 0x0a, 0x03, 0x72, 0x61, 0x6d,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x41, 0x4d, 0x52,
	0x03, 0x72, 0x61, 0x6d, 0x12, 0x19, 0x0a, 0x03, 0x67, 0x70, 0x75, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x50, 0x55, 0x52, 0x03, 0x67, 0x70, 0x75, 0x12,
	0x25, 0x0a, 0x07, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x52, 0x07, 0x62,
	0x61, 0x74, 0x74, 0x65, 0x72, 0x79, 0x12, 0x25, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x3e, 0x0a,
	0x10, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x0f, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x22, 0x0a,
	0x06, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x52, 0x06, 0x73, 0x63, 0x72, 0x65, 0x65,
	0x6e, 0x12, 0x22, 0x0a, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x06, 0x63,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x2a, 0x27, 0x0a, 0x07, 0x44, 0x44, 0x52, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x44,
	0x44, 0x52, 0x33, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x44, 0x52, 0x34, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x44, 0x44, 0x52, 0x35, 0x10, 0x02, 0x2a, 0x2a, 0x0a, 0x04, 0x55, 0x6e, 0x69,
	0x74, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x6e, 0x69, 0x74, 0x4d, 0x42, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x55, 0x6e, 0x69, 0x74, 0x47, 0x42, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x6e, 0x69,
	0x74, 0x54, 0x42, 0x10, 0x02, 0x2a, 0x1f, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x53, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x48, 0x44, 0x44, 0x10, 0x02, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cellphone_proto_rawDescOnce sync.Once
	file_cellphone_proto_rawDescData = file_cellphone_proto_rawDesc
)

func file_cellphone_proto_rawDescGZIP() []byte {
	file_cellphone_proto_rawDescOnce.Do(func() {
		file_cellphone_proto_rawDescData = protoimpl.X.CompressGZIP(file_cellphone_proto_rawDescData)
	})
	return file_cellphone_proto_rawDescData
}

var file_cellphone_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_cellphone_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cellphone_proto_goTypes = []interface{}{
	(DDRType)(0),                  // 0: pb.DDRType
	(Unit)(0),                     // 1: pb.Unit
	(StorageType)(0),              // 2: pb.StorageType
	(*CPU)(nil),                   // 3: pb.CPU
	(*Battery)(nil),               // 4: pb.Battery
	(*RAM)(nil),                   // 5: pb.RAM
	(*Storage)(nil),               // 6: pb.Storage
	(*OperatingSystem)(nil),       // 7: pb.OperatingSystem
	(*GPU)(nil),                   // 8: pb.GPU
	(*Screen)(nil),                // 9: pb.Screen
	(*Camera)(nil),                // 10: pb.Camera
	(*Cellphone)(nil),             // 11: pb.Cellphone
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_cellphone_proto_depIdxs = []int32{
	1,  // 0: pb.RAM.unit:type_name -> pb.Unit
	0,  // 1: pb.RAM.ddr_type:type_name -> pb.DDRType
	1,  // 2: pb.Storage.unit:type_name -> pb.Unit
	2,  // 3: pb.Storage.storage_type:type_name -> pb.StorageType
	1,  // 4: pb.GPU.memory_unit:type_name -> pb.Unit
	3,  // 5: pb.Cellphone.cpu:type_name -> pb.CPU
	5,  // 6: pb.Cellphone.ram:type_name -> pb.RAM
	8,  // 7: pb.Cellphone.gpu:type_name -> pb.GPU
	4,  // 8: pb.Cellphone.battery:type_name -> pb.Battery
	6,  // 9: pb.Cellphone.storage:type_name -> pb.Storage
	7,  // 10: pb.Cellphone.operating_system:type_name -> pb.OperatingSystem
	9,  // 11: pb.Cellphone.screen:type_name -> pb.Screen
	10, // 12: pb.Cellphone.camera:type_name -> pb.Camera
	12, // 13: pb.Cellphone.created_at:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_cellphone_proto_init() }
func file_cellphone_proto_init() {
	if File_cellphone_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cellphone_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cellphone_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Battery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cellphone_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RAM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cellphone_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Storage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cellphone_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperatingSystem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cellphone_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cellphone_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Screen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cellphone_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Camera); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cellphone_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cellphone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cellphone_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cellphone_proto_goTypes,
		DependencyIndexes: file_cellphone_proto_depIdxs,
		EnumInfos:         file_cellphone_proto_enumTypes,
		MessageInfos:      file_cellphone_proto_msgTypes,
	}.Build()
	File_cellphone_proto = out.File
	file_cellphone_proto_rawDesc = nil
	file_cellphone_proto_goTypes = nil
	file_cellphone_proto_depIdxs = nil
}
